### ISSUE TITLE
[Express] colours instead of prefix

### ISSUE THREAD

**Issue by sebmandal** [tycrek/tlog#1]
You could change the color of [Express] instead of including a prefix of "warn" or etc. as the prefixes screw up the alignment of the proceeding text. Image to demonstrate this issue is attached below.
<img width="124" alt="Screen_Shot_2021-07-10_at_3 38 23_AM" src="https://user-images.githubusercontent.com/68667029/125148390-35133e00-e132-11eb-9439-41f1b4dfb25e.png">

**Comment by tycrek** [comment]
done 
![image](https://user-images.githubusercontent.com/29926144/126274036-d2c8a470-cad9-403f-9379-f3008d5e7724.png)

**Comment by tycrek** [comment]
(Well done a while ago but forgot to close this)
